 query GET_TAGS($pageSize: Int) {
    tags (pagination: { page: 1, pageSize: $pageSize }) {
        data {
            id
            attributes {
                name
                path {
                    data {
                        attributes {
                        url
                        }
                    }
                }
                articleCount
            }
        }
    }
}