query GET_MAIN_MENU {
    mainmenu {
        items {
        	link: menulinks_id {
                id
                title
                url
                status
                sort
            }
        }
    }
}