query GET_TAG($id: String!){
    tags (filter: {id: {_eq: $id}, status: {_eq: "published"}}) {
        id
        name
        slug
        status
        articles {
            articles_id(filter: {status: {_eq: "published"}}) {
                id
                title
                cover_image {
                    id
                    folder {
                        name
                    }
                    filename_disk
                    filename_download
                    type
                    description
                    filesize
                }
                summary
                slug
            }
        }
	}
}