query GET_PATH($path: String!){
    articles (filter: {slug: {_eq: $path}}) {
        id
        title
        body
        tags {
            tag: tags_id {
                id
                name
                slug
            }
        }
	}
}