query GET_SIDE_MENU {
    sidemenu {
        items {
        	menulinks_id {
                id
                title
                url
                status
                sort
            }
        }
    }
}