query GET_TAG($id: ID!){
    tag: tags_by_id(id: $id) {
        id
        name
        slug
        status
        articles {
            article: articles_id {
                id
                title
                slug
            }
        }
	}
}