query GET_SIDE_MENU {
    sidemenu {
        items {
        	menulinks_id(filter: {status: {_eq: "published"}}) {
                id
                title
                url
                status
                sort
            }
        }
    }
}